version: "3.7"

services:
    rewardsapi:
        image: rewardsapi
        build: .
        command:
            [
                "sh",
                "-c",
                "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 -m uvicorn app.main:app --host 0.0.0.0 --port 5000 --reload",
            ]
        ports:
            - 5000:5000
            - 5678:5678
        env_file:
            - .env
        volumes:
            - .:/app
