"""
Claim .env config
"""

import os

CLAIM_VERIFICATION_API = os.environ["CLAIM_VERIFICATION_API"]
REWARD_CLAIM_FROM = os.environ["REWARD_CLAIM_FROM"]
REWARD_CLAIM_TO = os.environ["REWARD_CLAIM_TO"]
SENDGRID_API_KEY = os.environ["SENDGRID_API_KEY"]
POAP_API_KEY = os.environ["POAP_API_KEY"]
POAP_AUTH0_AUDIENCE = os.environ["POAP_AUTH0_AUDIENCE"]
POAP_AUTH0_CLIENT_ID = os.environ["POAP_AUTH0_CLIENT_ID"]
POAP_AUTH0_CLIENT_SECRET = os.environ["POAP_AUTH0_CLIENT_SECRET"]
POAP_SECRETS = os.environ["POAP_SECRETS"]
