"""
Claim .env config
"""

import os

CLAIM_VERIFICATION_API = os.environ["CLAIM_VERIFICATION_API"]
REWARD_CLAIM_FROM = os.environ["REWARD_CLAIM_FROM"]
REWARD_CLAIM_TO = os.environ["REWARD_CLAIM_TO"]
SENDGRID_API_KEY = os.environ["SENDGRID_API_KEY"]
POAP_API_KEY = os.environ["POAP_API_KEY"]
POAP_OAUTH_KEY = os.environ["POAP_OAUTH_KEY"]
POAP_SECRETS = os.environ["POAP_SECRETS"]
